apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: backend
          image: your-backend-image:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
          # Add other environment variables
        - name: frontend
          image: your-frontend-image:latest
          ports:
            - containerPort: 3000
